[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false
verbosity = 1
fuzz = { runs = 1000 }
invariant = { runs = 256, depth = 15, fail_on_revert = false, call_override = false }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
